use_frameworks!

platform :ios, '9.0'

target 'LTNetworking_Example' do
  pod 'LTNetworking', :path => '/Users/hanxiaojie/Documents/GitHub/LTNetworking'

  target 'LTNetworking_Tests' do
    inherit! :search_paths
  end
end
