use_frameworks!

platform :ios, '8.0'

target 'LTNetworking_Example' do
  pod 'LTNetworking', :path => '../'

  target 'LTNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
